[character]
success_symbol = "➜"
error_symbol = "✗"

[git_status]
style = "bold dimmed"

[cmd_duration]
min_time = 10

[package]
disabled = true

[nodejs]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 20
style = "bold yellow"
